version: '3.8'

services:
  uniguide:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniguide_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - uniguide_data:/app/data

volumes:
  uniguide_data:
